# Site settings
title: Think More
email: yangchen@thinkmore.info
description: > # this means to ignore newlines until "baseurl:"
    Personal thoughts and work log in software development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yangchen
github_username:  wao

# Build settings
markdown: kramdown
