# Site settings
title: Think More
email: yangchen@thinkmore.info
description: > # this means to ignore newlines until "baseurl:"
    Personal thoughts and work log in software development.
baseurl: "/thinkmore" # the subpath of your site, e.g. /blog/
url: "http://wao.github.io" # the base hostname & protocol for your site
twitter_username: yangchen
github_username:  wao

# Build settings
markdown: kramdown

# Tagging
tag_page_layout: tag_page
tag_page_dir: tag
